// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFHcuHkevZwjZG32qjymO2WdNunDuURJI',
    appId: '1:419250565627:web:64d1e549773ee816489b5e',
    messagingSenderId: '419250565627',
    projectId: 'my-authentication-ea4f4',
    authDomain: 'my-authentication-ea4f4.firebaseapp.com',
    storageBucket: 'my-authentication-ea4f4.appspot.com',
    measurementId: 'G-LQH85391Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMoDDsDajcRWZ563xcn6hkHMmlHzN5H5I',
    appId: '1:419250565627:android:ad71b4d71c7ac9ca489b5e',
    messagingSenderId: '419250565627',
    projectId: 'my-authentication-ea4f4',
    storageBucket: 'my-authentication-ea4f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDIiA02AFs8fXpTCqBUWxVAV1L_2SUi-g',
    appId: '1:419250565627:ios:852841479d438beb489b5e',
    messagingSenderId: '419250565627',
    projectId: 'my-authentication-ea4f4',
    storageBucket: 'my-authentication-ea4f4.appspot.com',
    iosBundleId: 'com.example.myAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDIiA02AFs8fXpTCqBUWxVAV1L_2SUi-g',
    appId: '1:419250565627:ios:16a53e6ef31ee2e8489b5e',
    messagingSenderId: '419250565627',
    projectId: 'my-authentication-ea4f4',
    storageBucket: 'my-authentication-ea4f4.appspot.com',
    iosBundleId: 'com.example.myAuthentication.RunnerTests',
  );
}
